# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "D:/Study/paper/EyeTracker/consumer/EyeTracker;D:/Study/paper/EyeTracker/consumer/EyeTracker/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/release/armeabi-v7a")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENTS_ALL "")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_GENERATOR "STGZ;TGZ;TZ")
set(CPACK_INSTALL_CMAKE_PROJECTS "D:/Study/paper/EyeTracker/consumer/EyeTracker/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/release/armeabi-v7a;drishtisdk;ALL;/")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/drishtisdk")
set(CPACK_MODULE_PATH "D:/Study/paper/EyeTracker/consumer/EyeTracker/src/examples/drishti-upload/cmake/Modules;C:/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/modules;C:/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/find;D:/Study/paper/EyeTracker/consumer/EyeTracker/cmake/Modules;C:/.hunter/_Base/f58bcf2/2e091e5/7031e6f/Install/cmake/module")
set(CPACK_NSIS_DISPLAY_NAME "drishtisdk")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_PACKAGE_NAME "drishtisdk")
set(CPACK_OUTPUT_CONFIG_FILE "D:/Study/paper/EyeTracker/consumer/EyeTracker/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/release/armeabi-v7a/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "dhirvonen@elucideye.com")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "D:/Study/paper/EyeTracker/consumer/EyeTracker/DESCRIPTION")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Drishti SDK")
set(CPACK_PACKAGE_FILE_NAME "drishtisdk-0.12.5-Android")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "drishtisdk")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "drishtisdk")
set(CPACK_PACKAGE_MAINTAINER "dhirvonen@elucideye.com")
set(CPACK_PACKAGE_NAME "drishtisdk")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "0.12.5")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "12")
set(CPACK_PACKAGE_VERSION_PATCH "5")
set(CPACK_RESOURCE_FILE_LICENSE "D:/Instrument/C++/cmake-3.13.1-win64-x64/share/cmake-3.13/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "D:/Instrument/C++/cmake-3.13.1-win64-x64/share/cmake-3.13/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "D:/Instrument/C++/cmake-3.13.1-win64-x64/share/cmake-3.13/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "D:/Study/paper/EyeTracker/consumer/EyeTracker/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/release/armeabi-v7a/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "TRUE")
set(CPACK_SYSTEM_NAME "Android")
set(CPACK_TOPLEVEL_TAG "Android")
set(CPACK_WIX_SIZEOF_VOID_P "4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "D:/Study/paper/EyeTracker/consumer/EyeTracker/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/release/armeabi-v7a/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
